export const symbols = [
    { name: '<', value: '<' },
    { name: '>', value: '>' },
    { name: '\\nless', value: '\\nless' },
    { name: '\\ngtr', value: '\\ngtr' },
    { name: '\\leq', value: '\\leq' },
    { name: '\\geq', value: '\\geq' },
    { name: '\\leqslant', value: '\\leqslant' },
    { name: '\\geqslant', value: '\\geqslant' },
    { name: '\\nleq', value: '\\nleq' },
    { name: '\\ngeq', value: '\\ngeq' },
    { name: '\\nleqslant', value: '\\nleqslant' },
    { name: '\\ngeqslant', value: '\\ngeqslant' },
    { name: '\\prec', value: '\\prec' },
    { name: '\\succ', value: '\\succ' },
    { name: '\\nprec', value: '\\nprec' },
    { name: '\\nsucc', value: '\\nsucc' },
    { name: '\\preceq', value: '\\preceq' },
    { name: '\\succeq', value: '\\succeq' },
    { name: '\\npreceq', value: '\\npreceq' },
    { name: '\\nsucceq', value: '\\nsucceq' },
    { name: '\\ll', value: '\\ll' },
    { name: '\\gg', value: '\\gg' },
    { name: '\\lll', value: '\\lll' },
    { name: '\\ggg', value: '\\ggg' },
];
